
package tictactoeai.board.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import tictactoeai.AI.AI;
import tictactoeai.board.GridValues;

/**
 *
 * @author Liekkipipo-pc
 */
public class Grid extends javax.swing.JPanel {
    //false = circle, true = cross
    private boolean nextMove = true;
    private GridValues gv = new GridValues(15);
    private final int gridSideLength = 300;
    private AI bob;
    /**
     * Creates new form grid
     */
    public Grid() {
        bob = new AI(nextMove);
        addMove(7,7);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        addMove(evt.getX() / (gridSideLength/gv.getSideLength()), evt.getY() / (gridSideLength/gv.getSideLength()));
        Point p = bob.getMove(gv);
        addMove(p.x, p.y);
    }//GEN-LAST:event_formMouseClicked
    
    /**
     * add the next move
     * @param x x coordinate
     * @param y y coordinate
     */
    public void addMove(int x, int y) {
        gv.setSpace(x, y, nextMove);
        nextMove = !nextMove;
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        drawGrid(g);
        drawSymbols(g);       
    }
    
    private void drawGrid(Graphics g) {
        for (int x = 0; x <= gridSideLength; x += gridSideLength / 15) {
            g.drawLine(x, 0, x, gridSideLength);
            g.drawLine(0, x, gridSideLength, x);
        }
    }
    
    private void drawSymbols(Graphics g) {
        g.setColor(Color.black);
        for (int x = 0; x < gv.getSideLength(); x++) {
            for (int y = 0; y < gv.getSideLength(); y++) {
                if (gv.getGrid()[x][y] == null) {
                    continue;
                }
                else if (gv.getGrid()[x][y] == true) {
                    drawCross(x,y,g);
                }
                else if (gv.getGrid()[x][y] == false) {
                    drawCircle(x,y,g);
                }
            }
        }
    }
    
    private void drawCross(int x, int y, Graphics g) {
        g.setColor(Color.blue);
        x = x * (gridSideLength/gv.getSideLength());
        y = y * (gridSideLength/gv.getSideLength());
        g.drawLine(x, y, x+(gridSideLength/gv.getSideLength()), y+(gridSideLength/gv.getSideLength()));
        g.drawLine(x, y+(gridSideLength/gv.getSideLength()), x+(gridSideLength/gv.getSideLength()), y);
    }
    
    private void drawCircle(int x, int y, Graphics g) {
        g.setColor(Color.red);
        x = x * (gridSideLength/gv.getSideLength());
        y = y * (gridSideLength/gv.getSideLength());
        g.drawOval(x, y, (gridSideLength/gv.getSideLength()), (gridSideLength/gv.getSideLength()));
    }

    /**
     *
     * @return return the board
     */
    public GridValues getGv() {
        return gv;
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
